wip

diff --git a/.github/workflows/frontend-checks.yml b/.github/workflows/frontend-checks.yml
--- a/.github/workflows/frontend-checks.yml
+++ b/.github/workflows/frontend-checks.yml
@@ -17,6 +17,11 @@ jobs:
 
   screenshots:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        device: [ 'desktop', 'mobile' ]
+      # Make sure that one failing test does not cancel all other matrix jobs
+      fail-fast: false
     steps:
       - uses: actions/checkout@v2
       - uses: ./.github/actions/setup-node
@@ -33,7 +38,7 @@ jobs:
             sleep 0.1 # wait for 1/10 of the second before check again
           done
 
-          npm run screenshots
+          npm run screenshots # TODO:add device here
 
 
           kill "$foo"
@@ -45,5 +50,92 @@ jobs:
       - name: Upload screenshots
         uses: actions/upload-artifact@v2
         with:
-          name: e2e-screenshots-test # TODO: add device here
+          name: e2e-screenshots-${{ matrix.device }}
           path: screenshots/*.png
+
+  # This uploads the screenshots from both the (non-emulated) 'desktop' and
+  # 'mobile' runs.
+  upload-screenshots:
+    runs-on: ubuntu-latest
+
+    # don't upload screenshots on screenshot auto-update commits (to avoid screenshot-pushing
+    # loops), don't upload screenshots to main, and don't upload screenshots on release.
+    if: ${{ ! contains(github.event.head_commit.message,'Selenium screenshots auto-update') && github.ref != 'refs/heads/main' && ! startsWith(github.ref, 'refs/tags/release-') }}
+
+    # Run after all the tests completed successfully (and have uploaded their
+    # artifacts)
+    needs: screenshots
+
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          # set a PAT so that add-and-commit can trigger
+          # CI runs
+          token: ${{ secrets.GIX_BOT_PAT }}
+
+      # Make sure old screenshots don't pollute the commit
+      - run: rm -v -f screenshots/*.png
+
+      # Download the desktop screenshots artifacts
+      - uses: actions/download-artifact@v2
+        with:
+          name: e2e-screenshots-desktop
+          path: screenshots
+
+      # Download the mobile screenshots artifacts
+      - uses: actions/download-artifact@v2
+        with:
+          name: e2e-screenshots-mobile
+          path: screenshots
+
+      - run: |
+          echo "The following screenshots were recovered:"
+          shasum -a 256 screenshots/*.png | sort -k2 # sort by 2nd column (filename)
+
+      - name: "Revert screenshot changes smaller than 8 pixels and less"
+        run: |
+          for modified in $(git ls-files --modified ./screenshots)
+          do
+            echo found modified screenshot "$modified"
+            if [ ! -f "$modified" ]; then
+              # if the file cannot be found then git is probably just telling us that it was deleted.
+              # in that case we do _not_ revert the file and skip checking for its size.
+              echo "'$modified' not found, assuming it was deleted"
+              continue
+            fi
+            old=$(mktemp)
+            git show HEAD:$modified > $old
+            magick_out=$(mktemp)
+            metric=0
+            # The 'AE' metric counts the number of pixels that differ between the two images
+            # (we set /dev/null as the "diff" output image)
+            # NOTE: imagemagick prints the value to stderr
+            if ! compare -metric AE "$modified" "$old" /dev/null 2> "$magick_out"
+            then
+              metric=$(<"$magick_out")
+              echo "Magick AE is: '$metric'"
+            fi
+
+            rm "$magick_out"; rm "$old"
+
+            # Ensure that we got a meaningful output
+            if ! [[ $metric =~ ^[0-9]+$ ]]
+            then
+              echo "Magick didn't return a number: $metric"
+              exit 1
+            fi
+
+            if (( metric <= 30 ))
+            then
+              echo "Pixel difference ($metric) is too small, reverting"
+              git checkout HEAD -- "$modified"
+            fi
+          done
+
+      - name: Commit screenshots
+        uses: EndBug/add-and-commit@v9
+        with:
+          add: screenshots
+          default_author: github_actions
+          message: "🤖 Selenium screenshots auto-update"
+
